version: '3.9'

services:

# Container MySQL
  dbchat:
    image: mysql:8
    container_name: chatapp-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pswdbchat
      MYSQL_DATABASE: chatapp
      MYSQL_USER: chat_adm
      MYSQL_PASSWORD: pswdb
    ports:
      - "3309:3306" 
    networks:
      - chatapp  

# Container PHP
  chat_app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: chatapp
    volumes:
      - .:/var/www/html
    ports:
      - "5000:80" 
    depends_on:
      - dbchat
    networks:
      - chatapp

networks:
  chatapp:
    driver: bridge